---
sensors:
  holiday:
    Address: "thermostat/settings/holiday"
    Value: false
  override:
    Address: "thermostat/settings/override"
    Value: 18
actuators:
  expected:
    Address: "heater/expected"
    Value: 18
scheduleTopic: "thermostat/schedule"