---
scheduleTopic: "thermostat/schedule"
actuators:
  expected:
    address: "heater/expected"
    value: 18
settings:
  holiday:
    address: "thermostat/settings/holiday"
    value: false
  override:
    address: "thermostat/settings/override"
    value: 18
  mode:
    address: "thermostat/settings/mode"
    value: "auto"